apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: neonvm
    app.kubernetes.io/instance: virtualmachine-editor-role
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/part-of: neonvm
    rbac.authorization.k8s.io/aggregate-to-admin: 'true'
    rbac.authorization.k8s.io/aggregate-to-edit: 'true'
  name: neonvm-virtualmachine-editor-role
rules:
- apiGroups:
  - vm.neon.tech
  resources:
  - virtualmachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vm.neon.tech
  resources:
  - virtualmachines/status
  verbs:
  - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: neonvm
    app.kubernetes.io/instance: virtualmachine-viewer-role
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/part-of: neonvm
    rbac.authorization.k8s.io/aggregate-to-admin: 'true'
    rbac.authorization.k8s.io/aggregate-to-edit: 'true'
    rbac.authorization.k8s.io/aggregate-to-view: 'true'
  name: neonvm-virtualmachine-viewer-role
rules:
- apiGroups:
  - vm.neon.tech
  resources:
  - virtualmachines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vm.neon.tech
  resources:
  - virtualmachines/status
  verbs:
  - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: neonvm
    app.kubernetes.io/instance: virtualmachinemigration-editor-role
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/part-of: neonvm
    rbac.authorization.k8s.io/aggregate-to-admin: 'true'
    rbac.authorization.k8s.io/aggregate-to-edit: 'true'
  name: neonvm-virtualmachinemigration-editor-role
rules:
- apiGroups:
  - vm.neon.tech
  resources:
  - virtualmachinemigrations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vm.neon.tech
  resources:
  - virtualmachinemigrations/status
  verbs:
  - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: neonvm
    app.kubernetes.io/instance: virtualmachinemigration-viewer-role
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/part-of: neonvm
    rbac.authorization.k8s.io/aggregate-to-admin: 'true'
    rbac.authorization.k8s.io/aggregate-to-edit: 'true'
    rbac.authorization.k8s.io/aggregate-to-view: 'true'
  name: neonvm-virtualmachinemigration-viewer-role
rules:
- apiGroups:
  - vm.neon.tech
  resources:
  - virtualmachinemigrations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vm.neon.tech
  resources:
  - virtualmachinemigrations/status
  verbs:
  - get

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: neonvm
    app.kubernetes.io/instance: webhook-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: service
    app.kubernetes.io/part-of: neonvm
  name: neonvm-webhook-service
  namespace: neonvm-system
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    control-plane: controller

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/name: device-plugin
  name: neonvm-device-plugin
  namespace: neonvm-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: device-plugin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: device-plugin
    spec:
      containers:
      - args:
        - --log-level
        - info
        - --domain
        - neonvm
        - --device
        - "name: kvm\ngroups:\n  - count: 1000\n    paths:\n      - path: /dev/kvm\n"
        - --device
        - "name: vhost-net\ngroups:\n  - count: 1000\n    paths:\n      - path: /dev/vhost-net\n"
        image: docker.io/squat/generic-device-plugin@sha256:dc192e164c69b03f156765793a1be62ca437709ae477b27ca7d8f3dcf5021576
        name: generic-device-plugin
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 50m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 10Mi
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /var/lib/kubelet/device-plugins
          name: device-plugin
        - mountPath: /dev
          name: dev
      priorityClassName: system-node-critical
      tolerations:
      - effect: NoExecute
        operator: Exists
      - effect: NoSchedule
        operator: Exists
      volumes:
      - hostPath:
          path: /var/lib/kubelet/device-plugins
        name: device-plugin
      - hostPath:
          path: /dev
        name: dev
  updateStrategy:
    type: RollingUpdate

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/component: certificate
    app.kubernetes.io/created-by: neonvm
    app.kubernetes.io/instance: serving-cert
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: certificate
    app.kubernetes.io/part-of: neonvm
  name: neonvm-serving-cert
  namespace: neonvm-system
spec:
  dnsNames:
  - neonvm-webhook-service.neonvm-system.svc
  - neonvm-webhook-service.neonvm-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: neonvm-selfsigned-issuer
  secretName: webhook-server-cert

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    app.kubernetes.io/component: certificate
    app.kubernetes.io/created-by: neonvm
    app.kubernetes.io/instance: selfsigned-issuer
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: issuer
    app.kubernetes.io/part-of: neonvm
  name: neonvm-selfsigned-issuer
  namespace: neonvm-system
spec:
  selfSigned: {}

---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: neonvm-overlay-for-pods
  namespace: neonvm-system
spec:
  config: '{ "cniVersion": "0.3.1", "name": "overlay-for-pods", "type": "bridge",
    "bridge": "neon-br0", "ipam": { "type": "whereabouts", "range": "{{ .Values.network.podRange }}",
    "range_start": "{{ .Values.network.podRangeStart }}", "range_end": "{{ .Values.network.podRangeEnd }}" } }'

---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: neonvm-overlay-for-vms
  namespace: neonvm-system
spec:
  config: '{ "cniVersion": "0.3.1", "name": "overlay-for-vms", "type": "bridge", "bridge":
    "neon-br0", "ipam": {} }'

---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: neonvm-overlay-ipam
  namespace: neonvm-system
spec:
  config: '{ "ipam": { "network_name": "neonvm", "ipRanges": [ { "range": "{{ .Values.network.vmRange }}",
    "range_start": "{{ .Values.network.vmRangeStart }}" } ] } }'

---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: neonvm-system/neonvm-serving-cert
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: neonvm
    app.kubernetes.io/instance: mutating-webhook-configuration
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mutatingwebhookconfiguration
    app.kubernetes.io/part-of: neonvm
  name: neonvm-mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: neonvm-webhook-service
      namespace: neonvm-system
      path: /mutate-vm-neon-tech-v1-virtualmachine
  failurePolicy: Fail
  name: mvirtualmachine.kb.io
  rules:
  - apiGroups:
    - vm.neon.tech
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - virtualmachines
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: neonvm-webhook-service
      namespace: neonvm-system
      path: /mutate-vm-neon-tech-v1-virtualmachinemigration
  failurePolicy: Fail
  name: mvirtualmachinemigration.kb.io
  rules:
  - apiGroups:
    - vm.neon.tech
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - virtualmachinemigrations
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: neonvm-system/neonvm-serving-cert
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: neonvm
    app.kubernetes.io/instance: validating-webhook-configuration
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: validatingwebhookconfiguration
    app.kubernetes.io/part-of: neonvm
  name: neonvm-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: neonvm-webhook-service
      namespace: neonvm-system
      path: /validate-vm-neon-tech-v1-virtualmachine
  failurePolicy: Fail
  name: vvirtualmachine.kb.io
  rules:
  - apiGroups:
    - vm.neon.tech
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - virtualmachines
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: neonvm-webhook-service
      namespace: neonvm-system
      path: /validate-vm-neon-tech-v1-virtualmachinemigration
  failurePolicy: Fail
  name: vvirtualmachinemigration.kb.io
  rules:
  - apiGroups:
    - vm.neon.tech
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - virtualmachinemigrations
  sideEffects: None
